/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FanSignupRouteImport } from './routes/fan-signup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedBriefsRouteImport } from './routes/_authenticated.briefs'
import { Route as AuthenticatedCampaignBuilderRouteImport } from './routes/_authenticated.campaign-builder'
import { Route as AuthenticatedCampaignReportsRouteImport } from './routes/_authenticated.campaign-reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated.pricing'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedRacketDeskRouteImport } from './routes/_authenticated.racket-desk'
import { Route as AuthenticatedRosterBuilderRouteImport } from './routes/_authenticated.roster-builder'
import { Route as BrandsHowItWorksRouteImport } from './routes/brands.how-it-works'
import { Route as BriefSlugRouteImport } from './routes/brief.$slug'
import { Route as ReportSlugRouteImport } from './routes/report.$slug'
import { Route as RosterSlugRouteImport } from './routes/roster.$slug'
import { Route as SpotlightSlugRouteImport } from './routes/spotlight.$slug'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as VibeCheckIndexRouteImport } from './routes/vibe-check.index'
import { Route as VibeCheckBrandRouteImport } from './routes/vibe-check.brand'
import { Route as VibeCheckMusicianRouteImport } from './routes/vibe-check.musician'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminBriefFormRouteImport } from './routes/_authenticated.admin.brief-form'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated.admin.community'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated.admin.contact'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated.admin.emails'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated.admin.faqs'
import { Route as AuthenticatedAdminMailingRouteImport } from './routes/_authenticated.admin.mailing'
import { Route as AuthenticatedAdminProjectPlannerRouteImport } from './routes/_authenticated.admin.project-planner'
import { Route as AuthenticatedAdminSoundBoardRouteImport } from './routes/_authenticated.admin.sound-board'
import { Route as AuthenticatedAdminSpotlightsRouteImport } from './routes/_authenticated.admin.spotlights'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated.admin.traffic'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated.admin.usage'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminVibeCheckRouteImport } from './routes/_authenticated.admin.vibe-check'
import { Route as AuthenticatedBriefsIndexRouteImport } from './routes/_authenticated.briefs.index'
import { Route as AuthenticatedListeningReportIdRouteImport } from './routes/_authenticated.listening-report.$id'
import { Route as AuthenticatedRacketDeskIndexRouteImport } from './routes/_authenticated.racket-desk.index'
import { Route as AuthenticatedRacketDeskFanIntelRouteImport } from './routes/_authenticated.racket-desk.fan-intel'
import { Route as AuthenticatedRacketDeskProfilesRouteImport } from './routes/_authenticated.racket-desk.profiles'
import { Route as AuthenticatedRacketDeskReportsRouteImport } from './routes/_authenticated.racket-desk.reports'
import { Route as AuthenticatedRacketDeskSocialListeningRouteImport } from './routes/_authenticated.racket-desk.social-listening'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'
import { Route as ApiPublicTrackPageviewRouteImport } from './routes/api/public/track-pageview'
import { Route as ApiPublicTranscribeVoiceNoteRouteImport } from './routes/api/public/transcribe-voice-note'
import { Route as ApiPublicUploadBriefFileRouteImport } from './routes/api/public/upload-brief-file'
import { Route as ApiPublicWaitlistJoinRouteImport } from './routes/api/public/waitlist-join'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as AuthenticatedAdminSpotlightsIndexRouteImport } from './routes/_authenticated.admin.spotlights.index'
import { Route as AuthenticatedBriefsEditKeyRouteImport } from './routes/_authenticated.briefs.edit.$key'
import { Route as ApiPublicHooksReportMetricsWorkerRouteImport } from './routes/api/public/hooks/report-metrics-worker'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedAdminSpotlightsEditKeyRouteImport } from './routes/_authenticated.admin.spotlights.edit.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FanSignupRoute = FanSignupRouteImport.update({
  id: '/fan-signup',
  path: '/fan-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBriefsRoute = AuthenticatedBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignBuilderRoute =
  AuthenticatedCampaignBuilderRouteImport.update({
    id: '/campaign-builder',
    path: '/campaign-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignReportsRoute =
  AuthenticatedCampaignReportsRouteImport.update({
    id: '/campaign-reports',
    path: '/campaign-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRacketDeskRoute = AuthenticatedRacketDeskRouteImport.update({
  id: '/racket-desk',
  path: '/racket-desk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRosterBuilderRoute =
  AuthenticatedRosterBuilderRouteImport.update({
    id: '/roster-builder',
    path: '/roster-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const BrandsHowItWorksRoute = BrandsHowItWorksRouteImport.update({
  id: '/brands/how-it-works',
  path: '/brands/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefSlugRoute = BriefSlugRouteImport.update({
  id: '/brief/$slug',
  path: '/brief/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSlugRoute = ReportSlugRouteImport.update({
  id: '/report/$slug',
  path: '/report/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterSlugRoute = RosterSlugRouteImport.update({
  id: '/roster/$slug',
  path: '/roster/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightSlugRoute = SpotlightSlugRouteImport.update({
  id: '/spotlight/$slug',
  path: '/spotlight/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckIndexRoute = VibeCheckIndexRouteImport.update({
  id: '/vibe-check/',
  path: '/vibe-check/',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckBrandRoute = VibeCheckBrandRouteImport.update({
  id: '/vibe-check/brand',
  path: '/vibe-check/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckMusicianRoute = VibeCheckMusicianRouteImport.update({
  id: '/vibe-check/musician',
  path: '/vibe-check/musician',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBriefFormRoute =
  AuthenticatedAdminBriefFormRouteImport.update({
    id: '/brief-form',
    path: '/brief-form',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMailingRoute =
  AuthenticatedAdminMailingRouteImport.update({
    id: '/mailing',
    path: '/mailing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectPlannerRoute =
  AuthenticatedAdminProjectPlannerRouteImport.update({
    id: '/project-planner',
    path: '/project-planner',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSoundBoardRoute =
  AuthenticatedAdminSoundBoardRouteImport.update({
    id: '/sound-board',
    path: '/sound-board',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpotlightsRoute =
  AuthenticatedAdminSpotlightsRouteImport.update({
    id: '/spotlights',
    path: '/spotlights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVibeCheckRoute =
  AuthenticatedAdminVibeCheckRouteImport.update({
    id: '/vibe-check',
    path: '/vibe-check',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBriefsIndexRoute =
  AuthenticatedBriefsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBriefsRoute,
  } as any)
const AuthenticatedListeningReportIdRoute =
  AuthenticatedListeningReportIdRouteImport.update({
    id: '/listening-report/$id',
    path: '/listening-report/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRacketDeskIndexRoute =
  AuthenticatedRacketDeskIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRacketDeskRoute,
  } as any)
const AuthenticatedRacketDeskFanIntelRoute =
  AuthenticatedRacketDeskFanIntelRouteImport.update({
    id: '/fan-intel',
    path: '/fan-intel',
    getParentRoute: () => AuthenticatedRacketDeskRoute,
  } as any)
const AuthenticatedRacketDeskProfilesRoute =
  AuthenticatedRacketDeskProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedRacketDeskRoute,
  } as any)
const AuthenticatedRacketDeskReportsRoute =
  AuthenticatedRacketDeskReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedRacketDeskRoute,
  } as any)
const AuthenticatedRacketDeskSocialListeningRoute =
  AuthenticatedRacketDeskSocialListeningRouteImport.update({
    id: '/social-listening',
    path: '/social-listening',
    getParentRoute: () => AuthenticatedRacketDeskRoute,
  } as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackPageviewRoute = ApiPublicTrackPageviewRouteImport.update({
  id: '/api/public/track-pageview',
  path: '/api/public/track-pageview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeVoiceNoteRoute =
  ApiPublicTranscribeVoiceNoteRouteImport.update({
    id: '/api/public/transcribe-voice-note',
    path: '/api/public/transcribe-voice-note',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUploadBriefFileRoute =
  ApiPublicUploadBriefFileRouteImport.update({
    id: '/api/public/upload-brief-file',
    path: '/api/public/upload-brief-file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaitlistJoinRoute = ApiPublicWaitlistJoinRouteImport.update({
  id: '/api/public/waitlist-join',
  path: '/api/public/waitlist-join',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSpotlightsIndexRoute =
  AuthenticatedAdminSpotlightsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSpotlightsRoute,
  } as any)
const AuthenticatedBriefsEditKeyRoute =
  AuthenticatedBriefsEditKeyRouteImport.update({
    id: '/edit/$key',
    path: '/edit/$key',
    getParentRoute: () => AuthenticatedBriefsRoute,
  } as any)
const ApiPublicHooksReportMetricsWorkerRoute =
  ApiPublicHooksReportMetricsWorkerRouteImport.update({
    id: '/api/public/hooks/report-metrics-worker',
    path: '/api/public/hooks/report-metrics-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSpotlightsEditKeyRoute =
  AuthenticatedAdminSpotlightsEditKeyRouteImport.update({
    id: '/edit/$key',
    path: '/edit/$key',
    getParentRoute: () => AuthenticatedAdminSpotlightsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/briefs': typeof AuthenticatedBriefsRouteWithChildren
  '/campaign-builder': typeof AuthenticatedCampaignBuilderRoute
  '/campaign-reports': typeof AuthenticatedCampaignReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/racket-desk': typeof AuthenticatedRacketDeskRouteWithChildren
  '/roster-builder': typeof AuthenticatedRosterBuilderRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/report/$slug': typeof ReportSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/vibe-check/': typeof VibeCheckIndexRoute
  '/admin/brief-form': typeof AuthenticatedAdminBriefFormRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/mailing': typeof AuthenticatedAdminMailingRoute
  '/admin/project-planner': typeof AuthenticatedAdminProjectPlannerRoute
  '/admin/sound-board': typeof AuthenticatedAdminSoundBoardRoute
  '/admin/spotlights': typeof AuthenticatedAdminSpotlightsRouteWithChildren
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vibe-check': typeof AuthenticatedAdminVibeCheckRoute
  '/listening-report/$id': typeof AuthenticatedListeningReportIdRoute
  '/racket-desk/fan-intel': typeof AuthenticatedRacketDeskFanIntelRoute
  '/racket-desk/profiles': typeof AuthenticatedRacketDeskProfilesRoute
  '/racket-desk/reports': typeof AuthenticatedRacketDeskReportsRoute
  '/racket-desk/social-listening': typeof AuthenticatedRacketDeskSocialListeningRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/track-pageview': typeof ApiPublicTrackPageviewRoute
  '/api/public/transcribe-voice-note': typeof ApiPublicTranscribeVoiceNoteRoute
  '/api/public/upload-brief-file': typeof ApiPublicUploadBriefFileRoute
  '/api/public/waitlist-join': typeof ApiPublicWaitlistJoinRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/racket-desk/': typeof AuthenticatedRacketDeskIndexRoute
  '/briefs/edit/$key': typeof AuthenticatedBriefsEditKeyRoute
  '/api/public/hooks/report-metrics-worker': typeof ApiPublicHooksReportMetricsWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/spotlights/': typeof AuthenticatedAdminSpotlightsIndexRoute
  '/admin/spotlights/edit/$key': typeof AuthenticatedAdminSpotlightsEditKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/campaign-builder': typeof AuthenticatedCampaignBuilderRoute
  '/campaign-reports': typeof AuthenticatedCampaignReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roster-builder': typeof AuthenticatedRosterBuilderRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/report/$slug': typeof ReportSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/vibe-check': typeof VibeCheckIndexRoute
  '/admin/brief-form': typeof AuthenticatedAdminBriefFormRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/mailing': typeof AuthenticatedAdminMailingRoute
  '/admin/project-planner': typeof AuthenticatedAdminProjectPlannerRoute
  '/admin/sound-board': typeof AuthenticatedAdminSoundBoardRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vibe-check': typeof AuthenticatedAdminVibeCheckRoute
  '/listening-report/$id': typeof AuthenticatedListeningReportIdRoute
  '/racket-desk/fan-intel': typeof AuthenticatedRacketDeskFanIntelRoute
  '/racket-desk/profiles': typeof AuthenticatedRacketDeskProfilesRoute
  '/racket-desk/reports': typeof AuthenticatedRacketDeskReportsRoute
  '/racket-desk/social-listening': typeof AuthenticatedRacketDeskSocialListeningRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/track-pageview': typeof ApiPublicTrackPageviewRoute
  '/api/public/transcribe-voice-note': typeof ApiPublicTranscribeVoiceNoteRoute
  '/api/public/upload-brief-file': typeof ApiPublicUploadBriefFileRoute
  '/api/public/waitlist-join': typeof ApiPublicWaitlistJoinRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/briefs': typeof AuthenticatedBriefsIndexRoute
  '/racket-desk': typeof AuthenticatedRacketDeskIndexRoute
  '/briefs/edit/$key': typeof AuthenticatedBriefsEditKeyRoute
  '/api/public/hooks/report-metrics-worker': typeof ApiPublicHooksReportMetricsWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/spotlights': typeof AuthenticatedAdminSpotlightsIndexRoute
  '/admin/spotlights/edit/$key': typeof AuthenticatedAdminSpotlightsEditKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/briefs': typeof AuthenticatedBriefsRouteWithChildren
  '/_authenticated/campaign-builder': typeof AuthenticatedCampaignBuilderRoute
  '/_authenticated/campaign-reports': typeof AuthenticatedCampaignReportsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/racket-desk': typeof AuthenticatedRacketDeskRouteWithChildren
  '/_authenticated/roster-builder': typeof AuthenticatedRosterBuilderRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/report/$slug': typeof ReportSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/vibe-check/': typeof VibeCheckIndexRoute
  '/_authenticated/admin/brief-form': typeof AuthenticatedAdminBriefFormRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/mailing': typeof AuthenticatedAdminMailingRoute
  '/_authenticated/admin/project-planner': typeof AuthenticatedAdminProjectPlannerRoute
  '/_authenticated/admin/sound-board': typeof AuthenticatedAdminSoundBoardRoute
  '/_authenticated/admin/spotlights': typeof AuthenticatedAdminSpotlightsRouteWithChildren
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vibe-check': typeof AuthenticatedAdminVibeCheckRoute
  '/_authenticated/listening-report/$id': typeof AuthenticatedListeningReportIdRoute
  '/_authenticated/racket-desk/fan-intel': typeof AuthenticatedRacketDeskFanIntelRoute
  '/_authenticated/racket-desk/profiles': typeof AuthenticatedRacketDeskProfilesRoute
  '/_authenticated/racket-desk/reports': typeof AuthenticatedRacketDeskReportsRoute
  '/_authenticated/racket-desk/social-listening': typeof AuthenticatedRacketDeskSocialListeningRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/track-pageview': typeof ApiPublicTrackPageviewRoute
  '/api/public/transcribe-voice-note': typeof ApiPublicTranscribeVoiceNoteRoute
  '/api/public/upload-brief-file': typeof ApiPublicUploadBriefFileRoute
  '/api/public/waitlist-join': typeof ApiPublicWaitlistJoinRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/briefs/': typeof AuthenticatedBriefsIndexRoute
  '/_authenticated/racket-desk/': typeof AuthenticatedRacketDeskIndexRoute
  '/_authenticated/briefs/edit/$key': typeof AuthenticatedBriefsEditKeyRoute
  '/api/public/hooks/report-metrics-worker': typeof ApiPublicHooksReportMetricsWorkerRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/spotlights/': typeof AuthenticatedAdminSpotlightsIndexRoute
  '/_authenticated/admin/spotlights/edit/$key': typeof AuthenticatedAdminSpotlightsEditKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/briefs'
    | '/campaign-builder'
    | '/campaign-reports'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/racket-desk'
    | '/roster-builder'
    | '/brands/how-it-works'
    | '/brief/$slug'
    | '/report/$slug'
    | '/roster/$slug'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/vibe-check/'
    | '/admin/brief-form'
    | '/admin/community'
    | '/admin/contact'
    | '/admin/emails'
    | '/admin/faqs'
    | '/admin/mailing'
    | '/admin/project-planner'
    | '/admin/sound-board'
    | '/admin/spotlights'
    | '/admin/traffic'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/vibe-check'
    | '/listening-report/$id'
    | '/racket-desk/fan-intel'
    | '/racket-desk/profiles'
    | '/racket-desk/reports'
    | '/racket-desk/social-listening'
    | '/api/public/contact-submit'
    | '/api/public/track-pageview'
    | '/api/public/transcribe-voice-note'
    | '/api/public/upload-brief-file'
    | '/api/public/waitlist-join'
    | '/lovable/email/events'
    | '/admin/'
    | '/briefs/'
    | '/racket-desk/'
    | '/briefs/edit/$key'
    | '/api/public/hooks/report-metrics-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/spotlights/'
    | '/admin/spotlights/edit/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/campaign-builder'
    | '/campaign-reports'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/roster-builder'
    | '/brands/how-it-works'
    | '/brief/$slug'
    | '/report/$slug'
    | '/roster/$slug'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/vibe-check'
    | '/admin/brief-form'
    | '/admin/community'
    | '/admin/contact'
    | '/admin/emails'
    | '/admin/faqs'
    | '/admin/mailing'
    | '/admin/project-planner'
    | '/admin/sound-board'
    | '/admin/traffic'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/vibe-check'
    | '/listening-report/$id'
    | '/racket-desk/fan-intel'
    | '/racket-desk/profiles'
    | '/racket-desk/reports'
    | '/racket-desk/social-listening'
    | '/api/public/contact-submit'
    | '/api/public/track-pageview'
    | '/api/public/transcribe-voice-note'
    | '/api/public/upload-brief-file'
    | '/api/public/waitlist-join'
    | '/lovable/email/events'
    | '/admin'
    | '/briefs'
    | '/racket-desk'
    | '/briefs/edit/$key'
    | '/api/public/hooks/report-metrics-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/spotlights'
    | '/admin/spotlights/edit/$key'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/login'
    | '/partner'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/briefs'
    | '/_authenticated/campaign-builder'
    | '/_authenticated/campaign-reports'
    | '/_authenticated/dashboard'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/racket-desk'
    | '/_authenticated/roster-builder'
    | '/brands/how-it-works'
    | '/brief/$slug'
    | '/report/$slug'
    | '/roster/$slug'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/vibe-check/'
    | '/_authenticated/admin/brief-form'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/mailing'
    | '/_authenticated/admin/project-planner'
    | '/_authenticated/admin/sound-board'
    | '/_authenticated/admin/spotlights'
    | '/_authenticated/admin/traffic'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vibe-check'
    | '/_authenticated/listening-report/$id'
    | '/_authenticated/racket-desk/fan-intel'
    | '/_authenticated/racket-desk/profiles'
    | '/_authenticated/racket-desk/reports'
    | '/_authenticated/racket-desk/social-listening'
    | '/api/public/contact-submit'
    | '/api/public/track-pageview'
    | '/api/public/transcribe-voice-note'
    | '/api/public/upload-brief-file'
    | '/api/public/waitlist-join'
    | '/lovable/email/events'
    | '/_authenticated/admin/'
    | '/_authenticated/briefs/'
    | '/_authenticated/racket-desk/'
    | '/_authenticated/briefs/edit/$key'
    | '/api/public/hooks/report-metrics-worker'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/spotlights/'
    | '/_authenticated/admin/spotlights/edit/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  FanSignupRoute: typeof FanSignupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BrandsHowItWorksRoute: typeof BrandsHowItWorksRoute
  BriefSlugRoute: typeof BriefSlugRoute
  ReportSlugRoute: typeof ReportSlugRoute
  RosterSlugRoute: typeof RosterSlugRoute
  SpotlightSlugRoute: typeof SpotlightSlugRoute
  USlugRoute: typeof USlugRoute
  VibeCheckBrandRoute: typeof VibeCheckBrandRoute
  VibeCheckMusicianRoute: typeof VibeCheckMusicianRoute
  VibeCheckIndexRoute: typeof VibeCheckIndexRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  ApiPublicTrackPageviewRoute: typeof ApiPublicTrackPageviewRoute
  ApiPublicTranscribeVoiceNoteRoute: typeof ApiPublicTranscribeVoiceNoteRoute
  ApiPublicUploadBriefFileRoute: typeof ApiPublicUploadBriefFileRoute
  ApiPublicWaitlistJoinRoute: typeof ApiPublicWaitlistJoinRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicHooksReportMetricsWorkerRoute: typeof ApiPublicHooksReportMetricsWorkerRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-signup': {
      id: '/fan-signup'
      path: '/fan-signup'
      fullPath: '/fan-signup'
      preLoaderRoute: typeof FanSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/briefs': {
      id: '/_authenticated/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof AuthenticatedBriefsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-builder': {
      id: '/_authenticated/campaign-builder'
      path: '/campaign-builder'
      fullPath: '/campaign-builder'
      preLoaderRoute: typeof AuthenticatedCampaignBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-reports': {
      id: '/_authenticated/campaign-reports'
      path: '/campaign-reports'
      fullPath: '/campaign-reports'
      preLoaderRoute: typeof AuthenticatedCampaignReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/racket-desk': {
      id: '/_authenticated/racket-desk'
      path: '/racket-desk'
      fullPath: '/racket-desk'
      preLoaderRoute: typeof AuthenticatedRacketDeskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roster-builder': {
      id: '/_authenticated/roster-builder'
      path: '/roster-builder'
      fullPath: '/roster-builder'
      preLoaderRoute: typeof AuthenticatedRosterBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/brands/how-it-works': {
      id: '/brands/how-it-works'
      path: '/brands/how-it-works'
      fullPath: '/brands/how-it-works'
      preLoaderRoute: typeof BrandsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$slug': {
      id: '/brief/$slug'
      path: '/brief/$slug'
      fullPath: '/brief/$slug'
      preLoaderRoute: typeof BriefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$slug': {
      id: '/report/$slug'
      path: '/report/$slug'
      fullPath: '/report/$slug'
      preLoaderRoute: typeof ReportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$slug': {
      id: '/roster/$slug'
      path: '/roster/$slug'
      fullPath: '/roster/$slug'
      preLoaderRoute: typeof RosterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight/$slug': {
      id: '/spotlight/$slug'
      path: '/spotlight/$slug'
      fullPath: '/spotlight/$slug'
      preLoaderRoute: typeof SpotlightSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/': {
      id: '/vibe-check/'
      path: '/vibe-check'
      fullPath: '/vibe-check/'
      preLoaderRoute: typeof VibeCheckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/brand': {
      id: '/vibe-check/brand'
      path: '/vibe-check/brand'
      fullPath: '/vibe-check/brand'
      preLoaderRoute: typeof VibeCheckBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/musician': {
      id: '/vibe-check/musician'
      path: '/vibe-check/musician'
      fullPath: '/vibe-check/musician'
      preLoaderRoute: typeof VibeCheckMusicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brief-form': {
      id: '/_authenticated/admin/brief-form'
      path: '/brief-form'
      fullPath: '/admin/brief-form'
      preLoaderRoute: typeof AuthenticatedAdminBriefFormRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mailing': {
      id: '/_authenticated/admin/mailing'
      path: '/mailing'
      fullPath: '/admin/mailing'
      preLoaderRoute: typeof AuthenticatedAdminMailingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/project-planner': {
      id: '/_authenticated/admin/project-planner'
      path: '/project-planner'
      fullPath: '/admin/project-planner'
      preLoaderRoute: typeof AuthenticatedAdminProjectPlannerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sound-board': {
      id: '/_authenticated/admin/sound-board'
      path: '/sound-board'
      fullPath: '/admin/sound-board'
      preLoaderRoute: typeof AuthenticatedAdminSoundBoardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spotlights': {
      id: '/_authenticated/admin/spotlights'
      path: '/spotlights'
      fullPath: '/admin/spotlights'
      preLoaderRoute: typeof AuthenticatedAdminSpotlightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vibe-check': {
      id: '/_authenticated/admin/vibe-check'
      path: '/vibe-check'
      fullPath: '/admin/vibe-check'
      preLoaderRoute: typeof AuthenticatedAdminVibeCheckRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/briefs/': {
      id: '/_authenticated/briefs/'
      path: '/'
      fullPath: '/briefs/'
      preLoaderRoute: typeof AuthenticatedBriefsIndexRouteImport
      parentRoute: typeof AuthenticatedBriefsRoute
    }
    '/_authenticated/listening-report/$id': {
      id: '/_authenticated/listening-report/$id'
      path: '/listening-report/$id'
      fullPath: '/listening-report/$id'
      preLoaderRoute: typeof AuthenticatedListeningReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/racket-desk/': {
      id: '/_authenticated/racket-desk/'
      path: '/'
      fullPath: '/racket-desk/'
      preLoaderRoute: typeof AuthenticatedRacketDeskIndexRouteImport
      parentRoute: typeof AuthenticatedRacketDeskRoute
    }
    '/_authenticated/racket-desk/fan-intel': {
      id: '/_authenticated/racket-desk/fan-intel'
      path: '/fan-intel'
      fullPath: '/racket-desk/fan-intel'
      preLoaderRoute: typeof AuthenticatedRacketDeskFanIntelRouteImport
      parentRoute: typeof AuthenticatedRacketDeskRoute
    }
    '/_authenticated/racket-desk/profiles': {
      id: '/_authenticated/racket-desk/profiles'
      path: '/profiles'
      fullPath: '/racket-desk/profiles'
      preLoaderRoute: typeof AuthenticatedRacketDeskProfilesRouteImport
      parentRoute: typeof AuthenticatedRacketDeskRoute
    }
    '/_authenticated/racket-desk/reports': {
      id: '/_authenticated/racket-desk/reports'
      path: '/reports'
      fullPath: '/racket-desk/reports'
      preLoaderRoute: typeof AuthenticatedRacketDeskReportsRouteImport
      parentRoute: typeof AuthenticatedRacketDeskRoute
    }
    '/_authenticated/racket-desk/social-listening': {
      id: '/_authenticated/racket-desk/social-listening'
      path: '/social-listening'
      fullPath: '/racket-desk/social-listening'
      preLoaderRoute: typeof AuthenticatedRacketDeskSocialListeningRouteImport
      parentRoute: typeof AuthenticatedRacketDeskRoute
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-pageview': {
      id: '/api/public/track-pageview'
      path: '/api/public/track-pageview'
      fullPath: '/api/public/track-pageview'
      preLoaderRoute: typeof ApiPublicTrackPageviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe-voice-note': {
      id: '/api/public/transcribe-voice-note'
      path: '/api/public/transcribe-voice-note'
      fullPath: '/api/public/transcribe-voice-note'
      preLoaderRoute: typeof ApiPublicTranscribeVoiceNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-brief-file': {
      id: '/api/public/upload-brief-file'
      path: '/api/public/upload-brief-file'
      fullPath: '/api/public/upload-brief-file'
      preLoaderRoute: typeof ApiPublicUploadBriefFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist-join': {
      id: '/api/public/waitlist-join'
      path: '/api/public/waitlist-join'
      fullPath: '/api/public/waitlist-join'
      preLoaderRoute: typeof ApiPublicWaitlistJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/spotlights/': {
      id: '/_authenticated/admin/spotlights/'
      path: '/'
      fullPath: '/admin/spotlights/'
      preLoaderRoute: typeof AuthenticatedAdminSpotlightsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSpotlightsRoute
    }
    '/_authenticated/briefs/edit/$key': {
      id: '/_authenticated/briefs/edit/$key'
      path: '/edit/$key'
      fullPath: '/briefs/edit/$key'
      preLoaderRoute: typeof AuthenticatedBriefsEditKeyRouteImport
      parentRoute: typeof AuthenticatedBriefsRoute
    }
    '/api/public/hooks/report-metrics-worker': {
      id: '/api/public/hooks/report-metrics-worker'
      path: '/api/public/hooks/report-metrics-worker'
      fullPath: '/api/public/hooks/report-metrics-worker'
      preLoaderRoute: typeof ApiPublicHooksReportMetricsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/spotlights/edit/$key': {
      id: '/_authenticated/admin/spotlights/edit/$key'
      path: '/edit/$key'
      fullPath: '/admin/spotlights/edit/$key'
      preLoaderRoute: typeof AuthenticatedAdminSpotlightsEditKeyRouteImport
      parentRoute: typeof AuthenticatedAdminSpotlightsRoute
    }
  }
}

interface AuthenticatedAdminSpotlightsRouteChildren {
  AuthenticatedAdminSpotlightsIndexRoute: typeof AuthenticatedAdminSpotlightsIndexRoute
  AuthenticatedAdminSpotlightsEditKeyRoute: typeof AuthenticatedAdminSpotlightsEditKeyRoute
}

const AuthenticatedAdminSpotlightsRouteChildren: AuthenticatedAdminSpotlightsRouteChildren =
  {
    AuthenticatedAdminSpotlightsIndexRoute:
      AuthenticatedAdminSpotlightsIndexRoute,
    AuthenticatedAdminSpotlightsEditKeyRoute:
      AuthenticatedAdminSpotlightsEditKeyRoute,
  }

const AuthenticatedAdminSpotlightsRouteWithChildren =
  AuthenticatedAdminSpotlightsRoute._addFileChildren(
    AuthenticatedAdminSpotlightsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBriefFormRoute: typeof AuthenticatedAdminBriefFormRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminMailingRoute: typeof AuthenticatedAdminMailingRoute
  AuthenticatedAdminProjectPlannerRoute: typeof AuthenticatedAdminProjectPlannerRoute
  AuthenticatedAdminSoundBoardRoute: typeof AuthenticatedAdminSoundBoardRoute
  AuthenticatedAdminSpotlightsRoute: typeof AuthenticatedAdminSpotlightsRouteWithChildren
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVibeCheckRoute: typeof AuthenticatedAdminVibeCheckRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBriefFormRoute: AuthenticatedAdminBriefFormRoute,
  AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminMailingRoute: AuthenticatedAdminMailingRoute,
  AuthenticatedAdminProjectPlannerRoute: AuthenticatedAdminProjectPlannerRoute,
  AuthenticatedAdminSoundBoardRoute: AuthenticatedAdminSoundBoardRoute,
  AuthenticatedAdminSpotlightsRoute:
    AuthenticatedAdminSpotlightsRouteWithChildren,
  AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVibeCheckRoute: AuthenticatedAdminVibeCheckRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBriefsRouteChildren {
  AuthenticatedBriefsIndexRoute: typeof AuthenticatedBriefsIndexRoute
  AuthenticatedBriefsEditKeyRoute: typeof AuthenticatedBriefsEditKeyRoute
}

const AuthenticatedBriefsRouteChildren: AuthenticatedBriefsRouteChildren = {
  AuthenticatedBriefsIndexRoute: AuthenticatedBriefsIndexRoute,
  AuthenticatedBriefsEditKeyRoute: AuthenticatedBriefsEditKeyRoute,
}

const AuthenticatedBriefsRouteWithChildren =
  AuthenticatedBriefsRoute._addFileChildren(AuthenticatedBriefsRouteChildren)

interface AuthenticatedRacketDeskRouteChildren {
  AuthenticatedRacketDeskFanIntelRoute: typeof AuthenticatedRacketDeskFanIntelRoute
  AuthenticatedRacketDeskProfilesRoute: typeof AuthenticatedRacketDeskProfilesRoute
  AuthenticatedRacketDeskReportsRoute: typeof AuthenticatedRacketDeskReportsRoute
  AuthenticatedRacketDeskSocialListeningRoute: typeof AuthenticatedRacketDeskSocialListeningRoute
  AuthenticatedRacketDeskIndexRoute: typeof AuthenticatedRacketDeskIndexRoute
}

const AuthenticatedRacketDeskRouteChildren: AuthenticatedRacketDeskRouteChildren =
  {
    AuthenticatedRacketDeskFanIntelRoute: AuthenticatedRacketDeskFanIntelRoute,
    AuthenticatedRacketDeskProfilesRoute: AuthenticatedRacketDeskProfilesRoute,
    AuthenticatedRacketDeskReportsRoute: AuthenticatedRacketDeskReportsRoute,
    AuthenticatedRacketDeskSocialListeningRoute:
      AuthenticatedRacketDeskSocialListeningRoute,
    AuthenticatedRacketDeskIndexRoute: AuthenticatedRacketDeskIndexRoute,
  }

const AuthenticatedRacketDeskRouteWithChildren =
  AuthenticatedRacketDeskRoute._addFileChildren(
    AuthenticatedRacketDeskRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBriefsRoute: typeof AuthenticatedBriefsRouteWithChildren
  AuthenticatedCampaignBuilderRoute: typeof AuthenticatedCampaignBuilderRoute
  AuthenticatedCampaignReportsRoute: typeof AuthenticatedCampaignReportsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRacketDeskRoute: typeof AuthenticatedRacketDeskRouteWithChildren
  AuthenticatedRosterBuilderRoute: typeof AuthenticatedRosterBuilderRoute
  AuthenticatedListeningReportIdRoute: typeof AuthenticatedListeningReportIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBriefsRoute: AuthenticatedBriefsRouteWithChildren,
  AuthenticatedCampaignBuilderRoute: AuthenticatedCampaignBuilderRoute,
  AuthenticatedCampaignReportsRoute: AuthenticatedCampaignReportsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRacketDeskRoute: AuthenticatedRacketDeskRouteWithChildren,
  AuthenticatedRosterBuilderRoute: AuthenticatedRosterBuilderRoute,
  AuthenticatedListeningReportIdRoute: AuthenticatedListeningReportIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  FanSignupRoute: FanSignupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BrandsHowItWorksRoute: BrandsHowItWorksRoute,
  BriefSlugRoute: BriefSlugRoute,
  ReportSlugRoute: ReportSlugRoute,
  RosterSlugRoute: RosterSlugRoute,
  SpotlightSlugRoute: SpotlightSlugRoute,
  USlugRoute: USlugRoute,
  VibeCheckBrandRoute: VibeCheckBrandRoute,
  VibeCheckMusicianRoute: VibeCheckMusicianRoute,
  VibeCheckIndexRoute: VibeCheckIndexRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  ApiPublicTrackPageviewRoute: ApiPublicTrackPageviewRoute,
  ApiPublicTranscribeVoiceNoteRoute: ApiPublicTranscribeVoiceNoteRoute,
  ApiPublicUploadBriefFileRoute: ApiPublicUploadBriefFileRoute,
  ApiPublicWaitlistJoinRoute: ApiPublicWaitlistJoinRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicHooksReportMetricsWorkerRoute:
    ApiPublicHooksReportMetricsWorkerRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
