/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FanSignupRouteImport } from './routes/fan-signup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VibeCheckIndexRouteImport } from './routes/vibe-check.index'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as VibeCheckMusicianRouteImport } from './routes/vibe-check.musician'
import { Route as VibeCheckBrandRouteImport } from './routes/vibe-check.brand'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as SpotlightSlugRouteImport } from './routes/spotlight.$slug'
import { Route as PricingBrandsRouteImport } from './routes/pricing.brands'
import { Route as BrandsHowItWorksRouteImport } from './routes/brands.how-it-works'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FanSignupRoute = FanSignupRouteImport.update({
  id: '/fan-signup',
  path: '/fan-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckIndexRoute = VibeCheckIndexRouteImport.update({
  id: '/vibe-check/',
  path: '/vibe-check/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckMusicianRoute = VibeCheckMusicianRouteImport.update({
  id: '/vibe-check/musician',
  path: '/vibe-check/musician',
  getParentRoute: () => rootRouteImport,
} as any)
const VibeCheckBrandRoute = VibeCheckBrandRouteImport.update({
  id: '/vibe-check/brand',
  path: '/vibe-check/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightSlugRoute = SpotlightSlugRouteImport.update({
  id: '/spotlight/$slug',
  path: '/spotlight/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingBrandsRoute = PricingBrandsRouteImport.update({
  id: '/pricing/brands',
  path: '/pricing/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHowItWorksRoute = BrandsHowItWorksRouteImport.update({
  id: '/brands/how-it-works',
  path: '/brands/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/pricing/brands': typeof PricingBrandsRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/pricing/': typeof PricingIndexRoute
  '/vibe-check/': typeof VibeCheckIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/pricing/brands': typeof PricingBrandsRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/pricing': typeof PricingIndexRoute
  '/vibe-check': typeof VibeCheckIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/fan-signup': typeof FanSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/brands/how-it-works': typeof BrandsHowItWorksRoute
  '/pricing/brands': typeof PricingBrandsRoute
  '/spotlight/$slug': typeof SpotlightSlugRoute
  '/u/$slug': typeof USlugRoute
  '/vibe-check/brand': typeof VibeCheckBrandRoute
  '/vibe-check/musician': typeof VibeCheckMusicianRoute
  '/pricing/': typeof PricingIndexRoute
  '/vibe-check/': typeof VibeCheckIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/brands/how-it-works'
    | '/pricing/brands'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/pricing/'
    | '/vibe-check/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/brands/how-it-works'
    | '/pricing/brands'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/pricing'
    | '/vibe-check'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/connect'
    | '/contact'
    | '/fan-signup'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/results'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/brands/how-it-works'
    | '/pricing/brands'
    | '/spotlight/$slug'
    | '/u/$slug'
    | '/vibe-check/brand'
    | '/vibe-check/musician'
    | '/pricing/'
    | '/vibe-check/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  FanSignupRoute: typeof FanSignupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  TermsRoute: typeof TermsRoute
  BrandsHowItWorksRoute: typeof BrandsHowItWorksRoute
  PricingBrandsRoute: typeof PricingBrandsRoute
  SpotlightSlugRoute: typeof SpotlightSlugRoute
  USlugRoute: typeof USlugRoute
  VibeCheckBrandRoute: typeof VibeCheckBrandRoute
  VibeCheckMusicianRoute: typeof VibeCheckMusicianRoute
  PricingIndexRoute: typeof PricingIndexRoute
  VibeCheckIndexRoute: typeof VibeCheckIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-signup': {
      id: '/fan-signup'
      path: '/fan-signup'
      fullPath: '/fan-signup'
      preLoaderRoute: typeof FanSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/': {
      id: '/vibe-check/'
      path: '/vibe-check'
      fullPath: '/vibe-check/'
      preLoaderRoute: typeof VibeCheckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/musician': {
      id: '/vibe-check/musician'
      path: '/vibe-check/musician'
      fullPath: '/vibe-check/musician'
      preLoaderRoute: typeof VibeCheckMusicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibe-check/brand': {
      id: '/vibe-check/brand'
      path: '/vibe-check/brand'
      fullPath: '/vibe-check/brand'
      preLoaderRoute: typeof VibeCheckBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight/$slug': {
      id: '/spotlight/$slug'
      path: '/spotlight/$slug'
      fullPath: '/spotlight/$slug'
      preLoaderRoute: typeof SpotlightSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/brands': {
      id: '/pricing/brands'
      path: '/pricing/brands'
      fullPath: '/pricing/brands'
      preLoaderRoute: typeof PricingBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/how-it-works': {
      id: '/brands/how-it-works'
      path: '/brands/how-it-works'
      fullPath: '/brands/how-it-works'
      preLoaderRoute: typeof BrandsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  FanSignupRoute: FanSignupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  TermsRoute: TermsRoute,
  BrandsHowItWorksRoute: BrandsHowItWorksRoute,
  PricingBrandsRoute: PricingBrandsRoute,
  SpotlightSlugRoute: SpotlightSlugRoute,
  USlugRoute: USlugRoute,
  VibeCheckBrandRoute: VibeCheckBrandRoute,
  VibeCheckMusicianRoute: VibeCheckMusicianRoute,
  PricingIndexRoute: PricingIndexRoute,
  VibeCheckIndexRoute: VibeCheckIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
